### ISSUE TITLE
ParseError: "External ID not found in the system: base_report_to_printer.view_printing_users_prefs"

### ISSUE THREAD

**Issue by dceevp** [ingadhoc/reporting-engine#17]
hi,
i try to install the google_clout_print module and i get this error

--edited more info--
odoo v9
google_clout_printer v9 (download from git)
report to printer: i use odoo v9 base pre install module
server mode: download from git
local virtual box odoo 9

------------------------

Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/odoo/odoo-server/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 340, in load_modules
    loaded_modules, update_module)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 239, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/odoo/odoo-server/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/odoo/odoo-server/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 697, in _tag_record
    f_val = self.id_get(cr, f_ref)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 780, in id_get
    res = self.model_id_get(cr, id_str, raise_if_not_found)
  File "/odoo/odoo-server/openerp/tools/convert.py", line 791, in model_id_get
    raise_if_not_found=raise_if_not_found)
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 1002, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(cr, uid, xmlid)[1:3]
  File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "<decorator-gen-3>", line 2, in xmlid_lookup
  File "/odoo/odoo-server/openerp/tools/cache.py", line 85, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/odoo/odoo-server/openerp/addons/base/ir/ir_model.py", line 992, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % (xmlid))
ParseError: "External ID not found in the system: base_report_to_printer.view_printing_users_prefs" while parsing /odoo/odoo-server/addons/google_cloud_print/views/res_users_view.xml:30, near
<record model="ir.ui.view" id="view_users_form_simple_modif">
        <field name="name">res.users.form.printing</field>
        <field name="model">res.users</field>
        
        
        <field name="inherit_id" ref="base_report_to_printer.view_printing_users_prefs"/>
        <field name="arch" type="xml">
            <group name="printing" position="before">
                <group string="Google Cloud Print" name="gcp">
                    <field name="google_cloudprint_rtoken" invisible="1"/>
                    <label for="google_cloudprint_authorization_code"/>
                    <div class="oe_inline">
                        <field name="google_cloudprint_authorization_code" class="oe_inline"/>
                        <field name="google_cloudprint_uri" widget="url" text="&#8658; Generate Google Authorization Code" class="oe_inline oe_bold"/>
                        <button name="update_user_gc_printers" type="object" string="&#8658; Refresh Printers" class="oe_link" attrs="{'invisible': [('google_cloudprint_authorization_code', '=', False)]}"/>
                    </div>
                    <label for="gcprinter_ids" attrs="{'invisible': [('google_cloudprint_rtoken', '=', False)]}"/>
                    <div class="oe_inline" attrs="{'invisible': [('google_cloudprint_rtoken', '=', False)]}">
                        
                        <field name="gcprinter_ids" class="oe_inline" widget="many2many_tags" readonly="0"/>
                        
                        <a href="https://www.google.com/cloudprint#jobs" target="_blank">&#8658; Check Jobs on GCP</a>
                        <a href="https://www.google.com/cloudprint#printers" target="_blank">&#8658; Manage Printers on GCP</a>
                    </div>
                </group>
            </group>
        </field>
    </record>

could you help me?

**Comment by jjscarafia** [comment]
Have you read the ready? Are you using the mentioned repository? https://github.com/ingadhoc/reporting-engine/blob/9.0/google_cloud_print/README.rst

**Comment by dceevp** [comment]
I installed the patch module and work perfectly. thanks
